[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-server.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
