name: API for GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Daily at midnight

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Create API endpoint
        run: |
          mkdir -p api
          cat > api/health.json << 'EOF'
          {
            "status": "OK",
            "message": "Birthday app API is running!",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "environment": "GitHub Pages"
          }
          EOF

      - name: Deploy API
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
          destination_dir: api
